/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoExecutePanel: typeof import('./src/components/device/AutoExecutePanel.vue')['default']
    AutomationSidebar: typeof import('./src/components/device/AutomationSidebar.vue')['default']
    CaseStepLog: typeof import('./src/components/test/CaseStepLog.vue')['default']
    DeviceCard: typeof import('./src/components/device/DeviceCard.vue')['default']
    DeviceList: typeof import('./src/components/device/DeviceList.vue')['default']
    DeviceStatusBadge: typeof import('./src/components/device/DeviceStatusBadge.vue')['default']
    DiagnosticPanel: typeof import('./src/components/diagnostic/DiagnosticPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorAlert: typeof import('./src/components/common/ErrorAlert.vue')['default']
    FileTreeNode: typeof import('./src/components/FileTreeNode.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    PcAgentPanel: typeof import('./src/components/pc/PcAgentPanel.vue')['default']
    PcAuthPanel: typeof import('./src/components/pc/PcAuthPanel.vue')['default']
    PcCommandLog: typeof import('./src/components/pc/PcCommandLog.vue')['default']
    PcElementsList: typeof import('./src/components/pc/PcElementsList.vue')['default']
    PcModelPanel: typeof import('./src/components/pc/PcModelPanel.vue')['default']
    PcNeedUserBanner: typeof import('./src/components/pc/PcNeedUserBanner.vue')['default']
    PcPageInfo: typeof import('./src/components/pc/PcPageInfo.vue')['default']
    PcRunHistory: typeof import('./src/components/pc/PcRunHistory.vue')['default']
    PcScreenshotPanel: typeof import('./src/components/pc/PcScreenshotPanel.vue')['default']
    PcToolbar: typeof import('./src/components/pc/PcToolbar.vue')['default']
    PcUnifiedLog: typeof import('./src/components/pc/PcUnifiedLog.vue')['default']
    QuickActionsToolbar: typeof import('./src/components/test/QuickActionsToolbar.vue')['default']
    RouteErrorBoundary: typeof import('./src/components/common/RouteErrorBoundary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenCanvas: typeof import('./src/components/screen/ScreenCanvas.vue')['default']
    ScreenControls: typeof import('./src/components/screen/ScreenControls.vue')['default']
    ScreenToolbar: typeof import('./src/components/screen/ScreenToolbar.vue')['default']
    SkeletonList: typeof import('./src/components/common/SkeletonList.vue')['default']
    TerminalPanel: typeof import('./src/components/device/TerminalPanel.vue')['default']
    TestCaseExecutionReport: typeof import('./src/components/test/TestCaseExecutionReport.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
